platform :ios, '9.0'

target 'TodayNews' do

  use_frameworks!
inhibit_all_warnings!

pod 'Moya'
pod 'Alamofire'
pod 'SnapKit'
pod 'HandyJSON'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'Kingfisher'  #加载网络图片
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'SQLite.swift'
pod 'RxSwift'
pod 'RxCocoa'

end